repos:
  # Frontend: Prettier for JavaScript/TypeScript
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0  # Use the latest version of Prettier
    hooks:
      - id: prettier
        name: Prettier (Frontend)
        types: [javascript, file]
        exclude: ^ainalytics/  # Exclude backend files
        additional_dependencies:
          - prettier@3.1.0  # Specify the Prettier version

  # Backend: Ruff for Python formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.7  # Use the latest version of Ruff
    hooks:
      - id: ruff
        name: Ruff (Backend)
        exclude: ^webapp/  # Exclude frontend files
        args: [--fix]  # Automatically fix issues

  # Optional: Pre-commit hooks for general linting/formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
