"""Initial migration

Revision ID: a809faa745af
Revises: c0adef449ac2
Create Date: 2025-02-26 19:07:29.294474

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'a809faa745af'
down_revision: Union[str, None] = 'c0adef449ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
